export type ContextAction =
  | 'bought'
  | 'bridged'
  | 'deployed'
  | 'minted'
  | 'swapped'
  | 'sent'
  | 'received'
  | 'committed to'
  | 'received airdrop'
  | 'gave access to'
  | 'interacted with'
  | 'sent message'
  // WETH
  | 'wrapped'
  | 'unwrapped'
  // ENS
  | 'registered'
  | 'renewed'
  | 'set reverse ens to'
  // CryptoPunks
  | 'minted punk'
  | 'listed punk'
  | 'withdrew bid for'
  | 'bid on punk'
  | 'withdrew from contract'
  | 'bought punk'
  | 'transferred punk'
  | 'unlisted punk'
  // Leeroy
  | 'tipped'
  | 'updated user details'
  | 'replied to'
  | 'reposted'
  | 'registered username'
  | 'followed'
  | 'unfollowed'
  | 'posted'
  // fren.pet
  | 'set pet name'
  | 'bought accessory'
  | 'attacked'
  | 'redeemed'
  | 'bonk revealed'
  | 'wheel revealed'
  | 'wheel committed'
  | 'killed'
  | 'minted'
  | 'redeemed'
  | 'sold item'
  | 'joined dice game'
  | 'dice game settled'
  // Farcaster
  | 'registered a Farcaster ID'
  | 'changed recovery address to'
  | 'transferred Farcaster ID to'
  | 'rented'
  | 'removed a key'
  | 'removed a key for'
  | 'added a key'
  | 'added a key for';
