export type BridgeContextAction =
  | BridgeContextActionEnum.COMPLETED_A_CROSS_CHAIN_INTERACTION
  | BridgeContextActionEnum.INITIATED_A_CROSS_CHAIN_INTERACTION;

export enum BridgeContextActionEnum {
  COMPLETED_A_CROSS_CHAIN_INTERACTION = 'COMPLETED_A_CROSS_CHAIN_INTERACTION',
  INITIATED_A_CROSS_CHAIN_INTERACTION = 'INITIATED_A_CROSS_CHAIN_INTERACTION',
}
